name: allservice
description: "allservice mobile app."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  auto_route: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  analyzer: ^5.13.0
  intl: ^0.18.1
  intl_utils: ^2.8.5
  rxdart: ^0.27.7
  decimal: ^2.3.3
  shimmer_animation: ^2.1.0+1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  intl_translation: ^0.18.2
  flutter_svg: ^2.0.10+1
  appmetrica_plugin: ^2.0.0
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  toggle_switch: ^2.3.0
  pinput: ^5.0.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_secure_storage: ^4.2.1

flutter_icons:
  image_path: "assets/images/decoration/icon_ios.png"
  android: true 
  ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_background: "assets/images/decoration/icon_background.png"
  adaptive_icon_foreground: "assets/images/decoration/icon_foreground.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/splash.png"
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  injectable_generator: ^2.4.2
  freezed: ^2.4.6
  auto_route_generator: ^7.2.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
  fonts:
  - family: AllServiceIcons
    fonts:
      - asset: assets/fonts/AllServiceIcons.ttf

flutter_intl:
  enabled: true